[package]
name = "egui_tracing"
description = "Integrates tracing and logging with egui for event collection/visualization"
version = "0.1.0"
authors = ["Grievouz <tammo@ronke.dev>"]
edition = "2021"
license = "Unlicense"
repository = "https://github.com/grievouz/egui_tracing"
keywords = ["egui", "tracing", "log"]
categories = ["gui", "game-development"]

[dependencies]
chrono = { version = "0.4.24", default-features = false, features = ["clock"] }
egui = "0.22"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
unicode-segmentation = "1.10.1"

[dev-dependencies]
eframe = "0.22"
